Improve ReflectionUtil error messages.
fulcrumgenomics/commons pull request #28
Opened 2018-03-06 20:25 UTC by nh13

When no suitable one-arg string constructor was found, previously a
ClassNotFoundException was thrown with no helpful message.  Now we throw
a ReflectionException with the reason.

2018-03-06 20:25 UTC, nh13 commented on src/main/scala/com/fulcrumgenomics/commons/reflect/ReflectionUtil.scala
> +      throw new ReflectionException(s"Is this an Option[Option[...]]? Cannot construct an '${unitType.getSimpleName}'from a string: $value")
I added this in, since I want to know the string value too to help me figure out which one it was!

2018-03-06 20:50 UTC, tfenne commented on src/main/scala/com/fulcrumgenomics/commons/reflect/ReflectionUtil.scala
> +      }.orElse( Try {
I'm a little confused here, and think this probably needs tightening up.  E.g. what if in the above block there _is_ a String constructor but the value is invalid?  E.g. `clazz` == Double and values == `"hello"`.

2018-03-06 20:51 UTC, tfenne commented on src/main/scala/com/fulcrumgenomics/commons/reflect/ReflectionUtil.scala
> +        throw new ReflectionException(s"No suitable single-argument constructor found to construct a '${unitType.getSimpleName}' from a string: $value")
This isn't necessarily true - the constructor could have existed, but the call failed.

2018-03-06 20:51 UTC, tfenne requested changes
Thanks for cleaning this up!  Mind closing the last little hole?

2018-03-06 21:24 UTC, nh13 commented
@tfenne one last look?

2018-03-07 10:45 UTC, tfenne approved these changes
Thanks!

2018-04-10 17:05 UTC, merged