row.get returns Some(" ") instead of None when allowMissingColumn flag is set
fulcrumgenomics/commons pull request #66
Opened 2020-10-21 00:40 UTC by dsommer

row.get returns `Some(" ")` instead of `None` when `allowMissingColumn` flag is set to true and the field is empty. None is correctly returned when `allowMissingColumn` is not set.

2020-10-21 16:32 UTC, nh13 approved these changes

2020-10-21 16:32 UTC, nh13 commented on src/main/scala/com/fulcrumgenomics/commons/util/DelimitedDataParser.scala
>      * `allowMissingColumn` is true, then None is returned if the given column name is not present. */
I had to re-read this comment a few times to see what the intended behavior was.  I think will make it clearer, along with your bugfix.
```suggestion
  /** Gets a value from the specified column. If the value is null or empty returns None.  If
    * `allowMissingColumn` is true, then None is also returned if the given column name is not present. */
```

2020-10-21 16:32 UTC, nh13 commented on src/main/scala/com/fulcrumgenomics/commons/util/DelimitedDataParser.scala
> +    if (allowMissingColumn && ! headerIndices.contains(column)) None else get(headerIndices(column))
How about this? If you go with your implementation, please change `! headerIndices` to `!headerIndices`
```suggestion
    if (allowMissingColumn) headerIndices.get(column).flatMap(get[A]) else get(headerIndices(column))
```

2020-10-21 17:00 UTC, tfenne requested changes
Couple of simple suggestions.

2020-10-21 17:00 UTC, tfenne commented on src/test/scala/com/fulcrumgenomics/commons/util/DelimitedDataParserTest.scala
> +  it should "test empty fields returning None when allowMissingColumn is true" in {
the string should describe the intended behavior, not what the test should do.  So in this case perhaps:

```scala
it should "return None for missing values even with allowMissingColumn is true"
```

2020-10-21 17:00 UTC, tfenne commented on src/main/scala/com/fulcrumgenomics/commons/util/DelimitedDataParser.scala
> +    if (allowMissingColumn && ! headerIndices.contains(column)) None else get(headerIndices(column))
I find both a bit hard to follow.  I think I would suggest a more verbose approach that's a little easier to read:

```scala
headerIndices.get(column) match {
  case None      => if (allowMissingColumn) None else throw new NoSuchElementException(column)
  case Some(idx) => get[A](idx)
}
```

Either way it would be nice to avoid the double lookup of the column index for the common/positive path.

2020-10-21 17:19 UTC, dsommer commented
@tfenne I like the verbose match statement solution. Removed `if` statement and added another match case which seems even cleaner. 
```scala
    (headerIndices.get(column), allowMissingColumn) match {
      case (Some(idx), _) => get[A](idx)
      case (None, true)   => None
      case (None, false)  => throw new NoSuchElementException(column)
    }
```

2020-10-22 15:14 UTC, tfenne approved these changes

2020-10-22 15:15 UTC, merged